
"""
Generated by Rumoca.

This template renders the current DAE context into a SymPy-friendly symbolic
model. It keeps Rumoca's continuous equations in residual form and can solve
for explicit state derivatives and algebraics when possible.
"""

import sympy as sp


def der(symbol):
    if isinstance(symbol, sp.Indexed):
        return sp.IndexedBase(f"{symbol.base}_dot")[symbol.indices]
    if isinstance(symbol, sp.IndexedBase):
        return sp.IndexedBase(f"{symbol}_dot")
    return sp.Symbol(f"{symbol}_dot")


def pre(symbol):
    if isinstance(symbol, sp.Indexed):
        return sp.IndexedBase(f"pre_{symbol.base}")[symbol.indices]
    if isinstance(symbol, sp.IndexedBase):
        return sp.IndexedBase(f"pre_{symbol}")
    return sp.Symbol(f"pre_{symbol}")


def if_else(condition, then_expr, else_expr):
    return sp.Piecewise((then_expr, condition), (else_expr, True))


def _vector(entries):
    return (
        sp.Matrix([symbol for _, symbol, _ in entries]),
        {name: start for name, _, start in entries},
        {name: index for index, (name, _, _) in enumerate(entries)},
    )


def _column(entries):
    return sp.Matrix(entries) if entries else sp.Matrix([])


def zeros(*dims):
    if len(dims) == 1:
        return sp.Matrix.zeros(int(dims[0]), 1)
    return sp.Matrix.zeros(*(int(dim) for dim in dims))


def ones(*dims):
    if len(dims) == 1:
        return sp.Matrix.ones(int(dims[0]), 1)
    return sp.Matrix.ones(*(int(dim) for dim in dims))


def sum(values):
    if isinstance(values, sp.MatrixBase):
        return sp.Add(*list(values))
    if isinstance(values, (list, tuple)):
        return sp.Add(*values)
    return values


abs = sp.Abs
min = sp.Min
max = sp.Max
sign = sp.sign
sqrt = sp.sqrt
sin = sp.sin
cos = sp.cos
tan = sp.tan
asin = sp.asin
acos = sp.acos
atan = sp.atan
atan2 = sp.atan2
sinh = sp.sinh
cosh = sp.cosh
tanh = sp.tanh
exp = sp.exp
log = sp.log
log10 = lambda value: sp.log(value, 10)
floor = sp.floor
ceil = sp.ceiling
transpose = lambda value: sp.Matrix(value).T
identity = sp.eye
cross = lambda lhs, rhs: sp.Matrix(lhs).cross(sp.Matrix(rhs))
div = lambda lhs, rhs: sp.floor(lhs / rhs)
mod = sp.Mod
rem = sp.Mod


class Model:
    """Flattened symbolic DAE model."""

    def __init__(self):
        self.time = sp.Symbol("time")
        time = self.time

        # States, algebraics, inputs, outputs, parameters, constants, discretes.


        theta = sp.Symbol("theta")


        x = sp.Symbol("x")


        y = sp.Symbol("y")


        self.x, self.x_start, self.x_index = _vector([
            ("theta", theta, 0),
            ("x", x, 0),
            ("y", y, 0)
        ])



        omega_adj = sp.Symbol("omega_adj")


        tau = sp.Symbol("tau")


        self.y, self.y_start, self.y_index = _vector([
            ("omega_adj", omega_adj, 0),
            ("tau", tau, 0)
        ])


        self.u, self.u_start, self.u_index = _vector([])


        self.w, self.w_start, self.w_index = _vector([])



        T = sp.Symbol("T")


        T_fig8 = sp.Symbol("T_fig8")


        T_lobe = sp.Symbol("T_lobe")


        omega_turn = sp.Symbol("omega_turn")


        v_nom = sp.Symbol("v_nom")


        self.p, self.p_start, self.p_index = _vector([
            ("T", T, 35),
            ("T_fig8", T_fig8, (10 * pi)),
            ("T_lobe", T_lobe, (5 * pi)),
            ("omega_turn", omega_turn, 0.4),
            ("v_nom", v_nom, 2)
        ])



        pi = sp.Symbol("pi")


        self.constants, self.constants_start, self.constants_index = _vector([
            ("pi", pi, 3.141592653589793)
        ])


        self.z, self.z_start, self.z_index = _vector([])


        self.m, self.m_start, self.m_index = _vector([])


        self.x_dot_alias, self.x_dot_alias_start, self.x_dot_alias_index = _vector([])

        self.f_x = _column([
            (der(x) - (cos(theta) * v_nom)),
            (der(y) - (sin(theta) * v_nom)),
            (tau - (time - (T_fig8 * floor((time / T_fig8))))),
            (omega_adj - if_else((tau > T_lobe), (-omega_turn), omega_turn)),
            (der(theta) - omega_adj)
        ])

        self.initial_residuals = _column([])

        self.relations = _column([
            (tau > T_lobe)
        ])

        self.explicit_targets = [

            der(x),


            der(y),


            tau,


            omega_adj,


            der(theta),

        ]
        self.explicit_solution = None
        self.explicit_rhs = sp.Matrix([])

    def solve_explicit(self):
        """Best-effort symbolic solve for explicit derivatives and algebraics."""
        if len(self.f_x) == 0 or len(self.explicit_targets) == 0:
            self.explicit_solution = {}
            self.explicit_rhs = sp.Matrix([])
            return self.explicit_solution

        solutions = sp.solve(
            list(self.f_x),
            self.explicit_targets,
            dict=True,
            simplify=False,
        )
        self.explicit_solution = solutions[0] if solutions else {}
        self.explicit_rhs = sp.Matrix(
            [
                self.explicit_solution.get(symbol, symbol)
                for symbol in self.explicit_targets
            ]
        )
        return self.explicit_solution

    def summary(self):
        return {
            "states": [str(symbol) for symbol in self.x],
            "algebraics": [str(symbol) for symbol in self.y],
            "inputs": [str(symbol) for symbol in self.u],
            "parameters": [str(symbol) for symbol in self.p],
            "continuous_residual_count": len(self.f_x),
            "initial_residual_count": len(self.initial_residuals),
            "explicit_target_count": len(self.explicit_targets),
        }


if __name__ == "__main__":
    model = Model()
    print(model.summary())
    if len(model.f_x) > 0 and len(model.explicit_targets) > 0:
        print(model.solve_explicit())