function x_dot = SymDynamicsEuler6DoF(in1,in2,mass,L,in5)
%SymDynamicsEuler6DoF
%    X_DOT = SymDynamicsEuler6DoF(IN1,IN2,MASS,L,IN5)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    13-Apr-2025 05:42:24

I1 = in5(1,:);
I2 = in5(2,:);
I3 = in5(3,:);
T1 = in2(1,:);
T2 = in2(2,:);
T3 = in2(3,:);
gamma1 = in2(5,:);
theta1 = in1(7,:);
theta2 = in1(8,:);
theta3 = in1(9,:);
thrust_mag1 = in2(4,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
w1 = in1(10,:);
w2 = in1(11,:);
w3 = in1(12,:);
t2 = cos(gamma1);
t3 = cos(theta1);
t4 = cos(theta2);
t5 = cos(theta3);
t6 = sin(theta1);
t7 = sin(theta2);
t8 = sin(theta3);
t9 = -I3;
t10 = 1.0./mass;
t11 = 1.0./t7;
mt1 = [v1;v2;v3;t2.*t10.*(T1.*t4+T3.*t5.*t7+T2.*t7.*t8);t2.*t10.*(T2.*(t3.*t5-t4.*t6.*t8)-T3.*(t3.*t8+t4.*t5.*t6)+T1.*t6.*t7);-t2.*t10.*(-T2.*(t5.*t6+t3.*t4.*t8)+T3.*(t6.*t8-t3.*t4.*t5)+T1.*t3.*t7)-3.7114e-3;t5.*t11.*w3+t8.*t11.*w2;t5.*w2-t8.*w3;w1-t4.*t5.*t11.*w3-t4.*t8.*t11.*w2;(thrust_mag1.*sin(gamma1)+w2.*w3.*(I2+t9))./I1;-(w1.*w3.*(I1+t9)-L.*T3.*t2)./I2];
mt2 = [-(L.*T2.*t2-w1.*w2.*(I1-I2))./I3];
x_dot = [mt1;mt2];
end
