function x_dot = SymDynamicsEuler6DoF_convex_noumag(in1,in2,L,in4,alpha)
%SymDynamicsEuler6DoF_convex_noumag
%    X_DOT = SymDynamicsEuler6DoF_convex_noumag(IN1,IN2,L,IN4,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-May-2025 00:27:02

I1 = in4(1,:);
I2 = in4(2,:);
I3 = in4(3,:);
T1 = in2(1,:);
T2 = in2(2,:);
T3 = in2(3,:);
gamma1 = in2(4,:);
theta1 = in1(7,:);
theta2 = in1(8,:);
theta3 = in1(9,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
w1 = in1(10,:);
w2 = in1(11,:);
w3 = in1(12,:);
z1 = in1(13,:);
t2 = cos(gamma1);
t3 = cos(theta1);
t4 = cos(theta2);
t5 = cos(theta3);
t6 = exp(z1);
t7 = sin(theta1);
t8 = sin(theta2);
t9 = sin(theta3);
t10 = T1.^2;
t11 = T2.^2;
t12 = T3.^2;
t13 = -I3;
t14 = 1.0./t8;
t15 = t10+t11+t12;
t16 = sqrt(t15);
x_dot = [v1;v2;v3;t2.*(T1.*t4+T3.*t5.*t8+T2.*t8.*t9);t2.*(T2.*(t3.*t5-t4.*t7.*t9)-T3.*(t3.*t9+t4.*t5.*t7)+T1.*t7.*t8);-t2.*(-T2.*(t5.*t7+t3.*t4.*t9)+T3.*(t7.*t9-t3.*t4.*t5)+T1.*t3.*t8)-9.81e-3;t5.*t14.*w3+t9.*t14.*w2;t5.*w2-t9.*w3;w1-t4.*t5.*t14.*w3-t4.*t9.*t14.*w2;(t6.*t16.*sin(gamma1)+w2.*w3.*(I2+t13))./I1;-(w1.*w3.*(I1+t13)-L.*T3.*t2.*t6)./I2;(w1.*w2.*(I1-I2)-L.*T2.*t2.*t6)./I3;-alpha.*t16];
end
