function xdot = SymDynamics3DoF_linear(t,in2,in3,alpha)
%SymDynamics3DoF_linear
%    XDOT = SymDynamics3DoF_linear(T,IN2,IN3,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Apr-2025 20:13:01

thrust1 = in3(1,:);
thrust2 = in3(2,:);
thrust_mag1 = in3(3,:);
v1 = in2(3,:);
v2 = in2(4,:);
xdot = [v1;v2;thrust1;thrust2+3.7114e-3;-alpha.*thrust_mag1];
end
