function xdot = SymDynamics3DoF_mass_noumag(t,in2,in3,mass,L,I,alpha)
%SymDynamics3DoF_mass_noumag
%    XDOT = SymDynamics3DoF_mass_noumag(T,IN2,IN3,MASS,L,I,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    27-Apr-2025 21:16:45

m1 = in2(7,:);
theta1 = in2(5,:);
thrust1 = in3(1,:);
thrust2 = in3(2,:);
v1 = in2(3,:);
v2 = in2(4,:);
w1 = in2(6,:);
t2 = cos(theta1);
t3 = sin(theta1);
t4 = 1.0./m1;
xdot = [v1;v2;t4.*(t2.*thrust1-t3.*thrust2);t4.*(t2.*thrust2+t3.*thrust1)-3.7114e-3;w1;-(L.*thrust2)./I;-alpha.*sqrt(abs(thrust1).^2+abs(thrust2).^2)];
end
